global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'portcast-api-monitor'

scrape_configs:
  - job_name: 'portcast-api'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
